services:
  fcgi:
    build:
      context: .
      dockerfile: Dockerfile
#    ports:
#      - "52000:52000"
    networks:
      - backend

  httpd:
    image: "httpd:2.4.62"
    ports:
      - "8080:80"
    volumes:
      - "./httpd/httpd-local.conf:/usr/local/apache2/conf/httpd.conf"
      - "./src/site:/var/www"
    networks:
      - backend

  prometheus:
    build:
      context: src/prometheus/
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      - httpd
    networks:
      - backend

  grafana:
    image: "grafana/grafana-enterprise"
    ports:
      - '3000:3000'
    networks:
      - backend

networks:
  backend: